#!/bin/bash
#
# Simple script for displaying the battery level.
#

cd /sys/class/power_supply/BAT0/
while true; do
  status="$(cat status)"
  capacity="$(cat capacity)"
  if [[ "$status" = "Discharging" && "$capacity" -lt 15 ]]; then
    xterm -fn *-fixed-*-*-*-18-* -bg red -fg yellow \
        -geometry 38x1+1550+22 \
        -T "Battery low! Capacity: ${capacity}%" \
        -e 'read -n 1 -s -p "        Press key to exit..."'        
  fi
  sleep 300
done
