#!/bin/bash

# xrandr --output VGA1 --auto --scale-from 1366x768 --right-of LVDS1
# xrandr --output VGA1 --auto --right-of LVDS1
xrandr --output LVDS1 --auto --output VGA1 --auto --same-as LVDS1 --scale-from 1366x768
sleep 1
jwm -restart
