#!/bin/bash
#
# Simple script to update all 
#

while read -r line; do
  monitor="$(cut -f 5 -d ' ' <<< $line)"
  args="$args --output $monitor --auto"  
done <<< "$(xrandr --listmonitors)"

xrandr $args
sleep 1
jwm -restart
