#!/bin/bash

trap onsigint SIGINT

onsigint() {
  echo
  exit 1
}

# connect to wifi (default=miku)
printf "Connect to: "
read -r network
if [ -z $network ]; then
  network="miku"
fi

if [[ $network = "wired" ]]; then
  sudo dhcpcd > /dev/null
elif [[ $(netctl list) = *$network* ]]; then
  ~/.scripts/wifi $network
else
  echo "Network profile $network does not exist."
fi
# exit on failed connection
if [ $? -ne 0 ]; then exit 1; fi

# wait for keypress
echo
read -n 1 -s -p "Press key to exit..."
echo
